version: "3.3"

services:
  nginx:
    image: nginx:1.19
    container_name: ernst-handel-CLP-woocommerce-nginx
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - .:/var/www/html
      - ./dev/docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./dev/docker/nginx/log:/var/log/nginx
    working_dir: /var/www/html
    command: ['nginx', '-g', 'daemon off;']
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./dev/docker/php
      dockerfile: docker_php
    container_name: ernst-handel-CLP-woocommerce-backend-php
    volumes:
      - .:/var/www/html
      - ./dev/docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    depends_on:
      - mysql
  mysql:
    container_name: ernst-handel-CLP-woocommerce-backend-mysql
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: stage
      MYSQL_USER: stage
      MYSQL_PASSWORD: stage
      MYSQL_DATABASE: stage
    working_dir: /var/backup
    volumes:
      - ./dev/docker/mysql/database:/var/lib/mysql              # set directory for database
      - ./dev/docker/mysql/database_backup:/var/backup          # set directory with back up of database
  mailer:
    image: schickling/mailcatcher
    container_name: ernst-handel-CLP-woocommerce-backend-mailer
    ports: [ 1025, 1080 ]

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
